version: '3'
services:
  api-service:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3001
  client-service:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_KEY
    depends_on:
      - api-service