FROM node:9
ARG REACT_APP_API_KEY
ARG REACT_APP_SOCKET_URL

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY yarn.lock ./

RUN yarn install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

ENV NODE_ENV production
ENV REACT_APP_API_KEY $REACT_APP_API_KEY
ENV REACT_APP_SOCKET_URL $REACT_APP_SOCKET_URL

RUN yarn run build

EXPOSE 3001
CMD [ "npm", "start" ]