version: '3'
services:
  api-service:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 3001:3001
    environment:
      - YOUTUBE_API_KEY
    depends_on:
      - redis
  client-service:
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - api-service
  redis:
    image: redis:3.2-alpine