version: '3'
services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        - REACT_APP_API_KEY=${REACT_APP_API_KEY}
        - REACT_APP_SOCKET_URL=${REACT_APP_SOCKET_URL}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/client
    ports:
      - 3001:3001
    depends_on:
      - redis
  redis:
    image: redis:3.2-alpine